language: ruby
rvm:
  - 2.4.0

install:
  - bundle install
  - gem install jekyll
  - gem install jekyll-feed
  - gem install minima
  - gem install tzinfo
  - gem install tzinfo-data
  - gem install wdm

branches:
  only:
    - master

env:
  global:
    - JEKYLL_ENV=production

notifications:
  email:
    recipients:
      - ajaykarwal@gmail.com
    on_success: always
    on_failure: always

script:
  - chmod +x _scripts/build.sh
  - _scripts/build.sh

after_success:
  - chmod +x _scripts/deploy.sh
  - _scripts/deploy.sh

sudo: false
addons:
  apt:
    packages:
      - ncftp