title: darthVader | extinctCoder
description: |-
  sabbir ahmed shourov 's personal website
baseurl: ""
repository: extinctCoder/extinctCoder.github.io # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme: extinctCoder/extinctCoder.github.io

nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

port: 4040
host: 127.0.0.1
safe: false