baseURL = "https://extinctCoder.githb.io/"
languageCode = "en-us"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "about me"
  URL = "/about_me"
  weight = 1

  [[menu.header]]
  name = "portfolio"
  URL = "/portfolio"
  weight = 2

  [[menu.header]]
  name = "resume"
  URL = "/resume"
  weight = 3

  [[menu.header]]
  name = "download"
  URL = "/download"
  weight = 4

  [[menu.footer]]
  name = "facebook"
  URL = "https://www.facebook.com/extinctCoder"
  weight = 4

  [[menu.footer]]
  name = "github"
  URL = "https://www.github.com/extinctCoder"
  weight = 4

[params]

  googleTagManagerID = "GTM-54P42HW" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Andreas"
    text2 = "Ellure"

  [params.footer]
      copyright = "© darthVader. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"