# Generated by Django 3.0.5 on 2020-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepthome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='nick_name',
            field=models.CharField(default='nick_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(default='first_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(default='last_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middle_name',
            field=models.CharField(default='second_name', max_length=200),
        ),
    ]
